name: Publish to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Package to GitHub Registry
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          CI: true
