name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release PR
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.PAT }}
